### ISSUE TITLE
How to get the Spectrum Saliency Map and visualization it

### ISSUE THREAD

**Issue by CoderHHX** [yuyang-long/SSA#1]
Hi @yuyang-long and @qilong-zhang,

Thanks for your impressive work! I just have a question about how to obtain the Spectrum Saliency Map and visualize it, as indicated in your paper. I have not found those parts in your released codes.

Thanks.

**Comment by yuyang-long** [comment]
According to thedefinition of spectrum saliency map in Section 3.2, you can use the following code to visualize it.
```python
    grad_all = 0
    for images, images_ID,  gt_cpu in tqdm(data_loader):    
        print(images_ID[2])
        gt = gt_cpu.cuda()
        images = images.cuda()
        images = V(images, requires_grad=True)

        output_ = model(images)
        loss = F.cross_entropy(output, gt)
        loss.backward()
        grad = images.grad.data
        grad = gradgrad.mean(dim = 1).abs().sum(dim = 0).cpu().numpy()
        grad_all = grad_all + grad
        

    x = grad_all / 1000.0
    x = (x - x.min()) / (x.max() - x.min())
    g1 = sns.heatmap(x, cmap="rainbow")
    g1.set(yticklabels=[])  # remove the tick labels
    g1.set(ylabel=None)  # remove the axis label
    g1.set(xticklabels=[])  # remove the tick labels
    g1.set(xlabel=None)  # remove the axis label
    g1.tick_params(left=False)
    g1.tick_params(bottom=False)
    sns.despine(left=True, bottom=True)
    plt.show()
    plt.savefig("fig.png")
```

**Comment by yuyang-long** [comment]
According to the definition of spectrum saliency map in Section 3.2, you can use the following code to visualize it.
```python
    grad_all = 0
    for images, images_ID,  gt_cpu in tqdm(data_loader):    
        gt = gt_cpu.cuda()
        images = images.cuda()
        img_dct = dct.dct_2d(images)
        img_dct = V(img_dct, requires_grad = True)
        img_idct = dct.idct_2d(img_dct)

        output_ = model(img_idct)
        loss = F.cross_entropy(output, gt)
        loss.backward()
        grad = img_dct.grad.data
        grad = grad.mean(dim = 1).abs().sum(dim = 0).cpu().numpy()
        grad_all = grad_all + grad
        

    x = grad_all / 1000.0
    x = (x - x.min()) / (x.max() - x.min())
    g1 = sns.heatmap(x, cmap="rainbow")
    g1.set(yticklabels=[])  # remove the tick labels
    g1.set(ylabel=None)  # remove the axis label
    g1.set(xticklabels=[])  # remove the tick labels
    g1.set(xlabel=None)  # remove the axis label
    g1.tick_params(left=False)
    g1.tick_params(bottom=False)
    sns.despine(left=True, bottom=True)
    plt.show()
    plt.savefig("fig.png")
```

**Comment by CoderHHX** [comment]
Well received with thanks!

**Comment by Truman168** [comment]
> According to the definition of spectrum saliency map in Section 3.2, you can use the following code to visualize it.
> 
> ```python
>     grad_all = 0
>     for images, images_ID,  gt_cpu in tqdm(data_loader):    
>         gt = gt_cpu.cuda()
>         images = images.cuda()
>         img_dct = dct.dct_2d(images)
>         img_dct = V(img_dct, requires_grad = True)
>         img_idct = dct.idct_2d(img_dct)
> 
>         output_ = model(img_idct)
>         loss = F.cross_entropy(output, gt)
>         loss.backward()
>         grad = img_dct.grad.data
>         grad = grad.mean(dim = 1).abs().sum(dim = 0).cpu().numpy()
>         grad_all = grad_all + grad
>         
> 
>     x = grad_all / 1000.0
>     x = (x - x.min()) / (x.max() - x.min())
>     g1 = sns.heatmap(x, cmap="rainbow")
>     g1.set(yticklabels=[])  # remove the tick labels
>     g1.set(ylabel=None)  # remove the axis label
>     g1.set(xticklabels=[])  # remove the tick labels
>     g1.set(xlabel=None)  # remove the axis label
>     g1.tick_params(left=False)
>     g1.tick_params(bottom=False)
>     sns.despine(left=True, bottom=True)
>     plt.show()
>     plt.savefig("fig.png")
> ```

你好，我想问一下，为什么我不同攻击方法生成的saliency-map都是一样的呀，用的就是这个源码
