### ISSUE TITLE
Question about delta

### ISSUE THREAD

**Issue by Unkrible** [yuyang-long/SSA#2]
Hello,
According to Eq(6) in paper, $g = \nabla_{x} J ( T(x), y; \phi)$
In `attack.py/Line95`, $g = \nabla_{T(x)} J(T(x), y; \phi)$

Does this changed gradient make a difference?

**Comment by yuyang-long** [comment]
The changed gradient has little effect on the attack success rate, difference is only about 1%.  We do this mainly to speed up backpropagation.
