### ISSUE TITLE
about test in resnet

### ISSUE THREAD

**Issue by LinQinLiang** [yuyang-long/SSA#3]
hello! how do you test in resnet152? Maybe the mean and std normalization of Resnet is different from Inception net. and I wonder if I should change the experimental setting.
![6217469c9cada6a72683b3fa820b3a2](https://user-images.githubusercontent.com/45589968/195969383-f9fbde58-4180-4845-a257-2992795ac19a.png)
![d828fd6933f04ae6f5529d002ec62d2](https://user-images.githubusercontent.com/45589968/195969384-35a68fa3-9972-4049-8981-da38f60c0387.png)

**Comment by yuyang-long** [comment]
Use tf_resnet_v2_152 as substitute model.
